version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --legacy-peer-deps --force

  build:
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - CI=false npm run build

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/**/*
